#!/usr/bin/env node
// The Worker's assets, inlined as base64 into one generated module.
//
// Why inline rather than fetch or import:
//
//   - **Nothing may enter the Pages artifact.** The receipt must not change what
//     the marketing site ships or what `check-weight.mjs` measures, so the logo
//     cannot go in `public/`. The Worker serves it from its own `/bill/*` route
//     instead, which is the only path the Worker owns.
//   - **The page must not reach a third-party font CDN.** A receipt opened on a
//     slow phone inside an in-app browser should make one request to one origin.
//     So the woff2 faces are served by the Worker too.
//   - **The PDF needs TTF**, which `pdf-lib` can embed and subset and woff2 is
//     not. `LilitaOne-Regular.ttf` and `NunitoSans-Variable.ttf` in
//     `worker/fonts/` were decompressed from the very woff2 files `@fontsource`
//     already ships in this repo's dependency tree — no font was downloaded, and
//     both are OFL.
//
// **Lilita One has no rupee sign in any subset it ships**, which is why the PDF
// draws every amount in Nunito Sans and keeps the display face for text that
// carries no currency — the outlet name and the word "Total".
//
// Run `npm run worker:assets` after changing the logo or a font.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const repo = path.resolve(here, '../..')

const sources = {
  LOGO_PNG: 'src/assets/brand/logo.png',
  LILITA_WOFF2: 'node_modules/@fontsource/lilita-one/files/lilita-one-latin-400-normal.woff2',
  NUNITO_WOFF2:
    'node_modules/@fontsource-variable/nunito-sans/files/nunito-sans-latin-wght-normal.woff2',
  // **Both Nunito ranges, because neither one is enough.** `@fontsource` splits
  // its fonts by unicode range, and no single file carries both the digits and
  // the rupee sign: `latin` has the digits, `latin-ext` has `₹`. A browser
  // stitches the two together through two `@font-face` rules. A PDF has to embed
  // real fonts and choose one per glyph, so the Worker embeds both and falls
  // back per character. Found by looking at the output: `latin` alone drew every
  // `₹` as a missing-glyph box, and swapping to `latin-ext` turned every digit
  // into one instead.
  NUNITO_EXT_WOFF2:
    'node_modules/@fontsource-variable/nunito-sans/files/nunito-sans-latin-ext-wght-normal.woff2',
  LILITA_TTF: 'worker/fonts/LilitaOne-Regular.ttf',
  NUNITO_TTF: 'worker/fonts/NunitoSans-Regular.ttf',
  NUNITO_EXT_TTF: 'worker/fonts/NunitoSans-Ext.ttf',
}

const lines = [
  '// GENERATED by worker/scripts/build-assets.mjs — do not edit.',
  '//',
  '// The logo and the brand faces, base64-encoded so the Worker can serve them',
  '// from its own route without touching the Pages artifact, and so `pdf-lib` can',
  '// embed and subset the TTFs. Regenerate with `npm run worker:assets`.',
  '',
]

let total = 0
for (const [name, relative] of Object.entries(sources)) {
  const file = path.join(repo, relative)
  if (!fs.existsSync(file)) {
    console.error(`✗ missing asset: ${relative}`)
    process.exit(1)
  }
  const bytes = fs.readFileSync(file)
  total += bytes.length
  lines.push(`/** \`${relative}\` — ${bytes.length} bytes. */`)
  lines.push(`export const ${name}_BASE64 =`)
  lines.push(`  '${bytes.toString('base64')}'`)
  lines.push('')
}

lines.push('/** base64 → bytes, without Node APIs a Worker does not have. */')
lines.push('export function decodeBase64(base64: string): Uint8Array {')
lines.push('  const binary = atob(base64)')
lines.push('  const bytes = new Uint8Array(binary.length)')
lines.push('  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i)')
lines.push('  return bytes')
lines.push('}')
lines.push('')

const out = path.join(repo, 'worker/src/assets.generated.ts')
fs.writeFileSync(out, lines.join('\n'), 'utf8')
console.log(`Wrote ${path.relative(repo, out)} — ${total} bytes of assets inlined.`)
